### ISSUE TITLE
Load Currency

### ISSUE THREAD

**Issue by navferty** [navferty/NavfertyExcelAddIn#12]

**Comment by uom42** [comment]
Что именно подразумевается ?

**Comment by navferty** [comment]
@uom42 что-то вроде [такого](https://pikabu.ru/story/kursyi_valyut_s_sayta_tsb_na_vba_s_avtoobnovleniem_7469372)

Правда, насколько я знаю возможность объявить user-defined function (UDF) на VSTO отсутствует (в отличие от VBA), поэтому, как вариант, по клику показывать форму с выбором валюты и даты, а значение будет помещено в активную ячейку.

**Comment by uom42** [comment]
Надо загружать курсы валют? или что тут надо?

**Comment by uom42** [comment]
Если сделать кнопочку "загрузить курс" то можно, но в формуле - куча подводных камней:

**Comment by uom42** [comment]
> @uom42 что-то вроде [такого](https://pikabu.ru/story/kursyi_valyut_s_sayta_tsb_na_vba_s_avtoobnovleniem_7469372)
> 
> Правда, насколько я знаю возможность объявить user-defined function (UDF) на VSTO отсутствует (в отличие от VBA), поэтому, как вариант, по клику показывать форму с выбором валюты и даты, а значение будет помещено в активную ячейку.

или кнопка обновить курс, которас смотрит формат ячейки и обновляет валюту по нему...

**Comment by navferty** [comment]
Делать через формулу - выглядит ненадёжно и трудно поддерживаемо. А в отсутствие UDF не вижу других вариантов, кроме как класть в ячейку числовое значение. Ретроспективно курс валюты не должен меняться, так что если в форме будет выбор валюты и даты - обновлять не нужно.
