### ISSUE TITLE
Icon redesign

### ISSUE THREAD

**Issue by IgorKhudiakov** [navferty/NavfertyExcelAddIn#36]
Before:
 ![image](https://user-images.githubusercontent.com/37725563/82492737-e317ef00-9b10-11ea-8623-8ae7775f498d.png)
After:
![image](https://user-images.githubusercontent.com/37725563/82493197-c03a0a80-9b11-11ea-8a39-cbc4e1d252c9.png)

Adapted for built-in themes.
- Dark Gray
![image](https://user-images.githubusercontent.com/37725563/82493259-e069c980-9b11-11ea-9ebd-97fb3206537a.png)
- Black
![image](https://user-images.githubusercontent.com/37725563/82493054-85d06d80-9b11-11ea-8fae-6ae29a9753da.png)

**Comment by navferty** [comment]
That's cool! Looking forward to see your pull request with new icons!
