### ISSUE TITLE
Extend transliteration feature with same letters replace

### ISSUE THREAD

**Issue by navferty** [navferty/NavfertyExcelAddIn#40]
Replace Cyrillic letters that look same to latin:

Cyrillic to latin letters shoul be replaced in such way:
```
АВЕКМНОРСТУХ -> ABEKMHOPCTYX
авекмнорстух -> abekmhopctyx
```

The `Transliterate` button on the ribbon should be expanded to splitButton with two options:
* 'в'->'v': transliteration
* 'в'->'b': replacement

`CyrillicToLatinFallback` should be renamed to `CyrillicToLatinTransliterationFallback`, and new class CyrillicToLatinReplacementFallback

**Comment by navferty** [comment]
"абвгдек" -> "aбbгдek" (a,b,e,k are latin, others - cyrillic)

**Comment by IgorKhudiakov** [comment]
The simplest solution is to make a complete analogy with transliteration.
Separately, I want to note that the logic of things is to replace only these lower-case letters: аеорсух, and not change the upper-case letter: У.

**Comment by navferty** [comment]
When this feature was requested, tha main goal was to provide converter for vehicle numbers. Letter У is present in Russian standard, ex. `У123МР` and that shuold be converted to `Y123MP`
