### ISSUE TITLE
Add function "amount in words"

### ISSUE THREAD

**Issue by Oalf72** [navferty/NavfertyExcelAddIn#48]
Add function "amount in words"

The idea is based on the need to write down the amount in words in contracts and payments.

Highly likely as is https://micro-solution.ru/projects/addin_vba-excel/summ_words
https://github.com/maestrow/amount-in-words
https://github.com/javadev/moneytostr-russian/blob/master/src/main/cs/MoneyToStr.cs
https://www.cyberforum.ru/vba/thread1463280.html

**Comment by navferty** [comment]
@Oalf72  Is that what you neaded?
https://github.com/navferty/NavfertyExcelAddIn/issues/42

Feature was implemented yesterday =)

**Comment by Oalf72** [comment]
tnx

**Comment by navferty** [comment]
Duplicate of #42
