### ISSUE TITLE
Excel 2019, "Вид" - нет значков!

### ISSUE THREAD

**Issue by uom42** [navferty/NavfertyExcelAddIn#82]
Tab "Вид" - отсутствуют значки!

![Скриншот 2021-07-04 00 12 41](https://user-images.githubusercontent.com/6280840/124362092-296cd680-dc5d-11eb-9e8b-2919d46fa70c.png)
###

**Comment by uom42** [comment]
При некоторой "узкой" ширине монитора (у меня второй монитор 1280*1024) не отображается текст кнопок в "вид", а т.к. у этих кнопок нет и значков - то не отображается ничего!
При ширине монитора 1920 - всё ок.

**Comment by navferty** [comment]
Надеюсь, с созданием значков поможет @IgorKhudiakov

**Comment by navferty** [comment]
Standard icons from ImageMso gallery were set to buttons, where custom images were missing
